version: '3'
services:

   db:
     image: postgres:9.6
     ports:
       - "5432"

   app:
     build:
       context: .
       dockerfile: Dockerfile
     command: /site/docker-utils/app-start.sh
     volumes:
       - .:/site/proj/
       - static-volume:/site/htdocs/static/
     ports:
       - "8000"
     environment:
       - DEBUG=True
       - DATABASE_URL=postgres://postgres@db/postgres
       - DJANGO_ENVIRONMENT_DIR=/site/
     stdin_open: true
     tty: true

   web:
     image: nginx:1.11
     ports:
       - "80:80"
       - "443:443"
     depends_on:
       - app
     volumes:
       - ./docker-utils/nginx/default.template.conf:/root/default.template.conf
       - ./docker-utils/ssl/:/site/ssl/
       - static-volume:/static
     command: /bin/bash -c "envsubst '$$NGINX_HTTP_PORT $$NGINX_HTTPS_PORT' < /root/default.template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
     environment:
       - NGINX_HOST=foobar.com
       - NGINX_HTTP_PORT=80
       - NGINX_HTTPS_PORT=443

volumes:
  static-volume:
