# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', django_cryptography.fields.encrypt(models.TextField(help_text='Secret message.'))),
                ('expire_date', models.DateTimeField(blank=True, help_text='The date and time that the secret will expire. If empty, it will not expire based on time.', null=True, verbose_name='Expiration Date')),
                ('expire_count', models.PositiveSmallIntegerField(default=0, help_text='The number of times this secret has been viewed', verbose_name='Expire Count')),
                ('expire_max_count', models.PositiveSmallIntegerField(default=1, help_text='The number of times this secret can be viewed before it expires. The default is 1.')),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
