# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='require_login',
            field=models.BooleanField(default=False, help_text='If checked, the user must be logged in to view.'),
        ),
    ]
