# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='expire_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='The number of times this secret can be viewed before it expires.'),
        ),
        migrations.AddField(
            model_name='secret',
            name='expire_date',
            field=models.DateTimeField(blank=True, help_text='The date and time that the secret will expire. If empty, it will not expire based on time.', null=True),
        ),
        migrations.AlterField(
            model_name='secret',
            name='text',
            field=models.TextField(help_text='Secret message.'),
        ),
    ]
