# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0002_auto_20180201_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='expire_max_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='The number of times this secret can be viewed before it expires. The default is 1.'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='expire_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='The number of times this secret has been viewed'),
        ),
    ]
