# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0002_secret_require_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='page_refresh',
            field=models.PositiveIntegerField(default=500, help_text='If an integer is provided, the page will refresh after the given number of seconds. The default is 500 seconds'),
        ),
    ]
