# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0003_auto_20180201_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
