# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0004_secret_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='expire_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='The number of times this secret has been viewed', verbose_name='Expire Count'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='expire_date',
            field=models.DateTimeField(blank=True, help_text='The date and time that the secret will expire. If empty, it will not expire based on time.', null=True, verbose_name='Expiration Date'),
        ),
    ]
